Fix Countdown
frc1418/frc1418.github.io pull request #623
Opened 2024-12-20 00:08 UTC by 1ceit

- Fix countdown by adding padStart
- Remove countdown div if the next event is not found
- Fix header blur
- Center menu items in menu dropdown
- Add 2024 page (not implemented yet)

2025-01-05 00:54 UTC, ErikBoesen approved these changes

2025-01-05 00:54 UTC, ErikBoesen commented on _data/team.yml
> +    image: "/images/team/wendy-abstone.png"
Why is this a different person's name

2025-01-05 00:54 UTC, ErikBoesen commented on _includes/footer.html
> +                <td><a href="https://alarm.com" target="_blank"><img  src="/images/sponsors/ADCLogo_horizontal.png"></a></td>
Could be nice to rename this image to match the format used by the other logos

2025-01-05 00:54 UTC, ErikBoesen commented on _includes/footer.html
> +                <td><a href="https://alarm.com" target="_blank"><img  src="/images/sponsors/ADCLogo_horizontal.png"></a></td>
But not a big deal

2025-01-05 00:54 UTC, ErikBoesen commented on images/Note/0013.png
Could you clarify why there's tons of identical images here?

2025-01-05 00:54 UTC, ErikBoesen commented on js/2024.js
> +document.addEventListener("DOMContentLoaded", function () {
Because the script tag that links this file is at the end of the document, this listener is unnecessary, you can just write the code directly

2025-01-05 00:54 UTC, ErikBoesen commented on js/2024.js
> +        if (frame < startTitleFrame) {
What if they're equal? Also might be cleaner to use some ternary operators to make the code a little cleaner

2025-01-05 00:54 UTC, ErikBoesen commented on js/2024.js
> +            title.style.opacity = '0';
This is repeated from a few lines earlier, I think

2025-01-05 00:55 UTC, ErikBoesen requested changes
Approval was accidental but it's almost ready

2025-01-09 18:00 UTC, 1ceit commented on _data/team.yml
> +    image: "/images/team/wendy-abstone.png"
she wanted a picture but didn't want to make one. She went through the catalogue and picked Wendy.

2025-01-09 18:01 UTC, 1ceit commented on _includes/footer.html
> +                <td><a href="https://alarm.com" target="_blank"><img  src="/images/sponsors/ADCLogo_horizontal.png"></a></td>
Yeah sorry I just dragged it from the zip with out editing.

2025-01-09 18:03 UTC, 1ceit commented on images/Note/0013.png
They are a frames of an animation.

2025-01-09 18:03 UTC, 1ceit commented on js/2024.js
> +document.addEventListener("DOMContentLoaded", function () {
Just habit sorry.

2025-01-09 18:13 UTC, 1ceit commented on js/2024.js
> +            title.style.opacity = '0';
I had the first as a place holder and didn't remove it.

2025-03-20 18:27 UTC, closed without merging